[project]
name = "moodle-mcp"
version = "0.3.0"
description = "A Model Context Protocol (MCP) server implementation that provides capabilities to interact with Moodle LMS."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "glom>=24.11.0",
    "mcp>=2,<3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]

[project.scripts]
moodle-mcp = "moodle_mcp.__main__:main"

[project.urls]
Homepage = "https://github.com/loyaniu/moodle-mcp"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
